//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndexTF3
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat
    {
        public int cha_id { get; set; }
        public string cha_hor { get; set; }
        public int cha_usu_id { get; set; }
        public string cha_men { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
