//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndexTF3
{
    using System;
    using System.Collections.Generic;
    
    public partial class itinerario
    {
        public int iti_id { get; set; }
        public int iti_des_id { get; set; }
        public int iti_usu_id { get; set; }
    
        public virtual destino destino { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
