//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndexTF3
{
    using System;
    using System.Collections.Generic;
    
    public partial class localidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public localidad()
        {
            this.destino = new HashSet<destino>();
        }
    
        public int loc_id { get; set; }
        public string loc_nom { get; set; }
        public int loc_dep_id { get; set; }
        public Nullable<int> loc_hab { get; set; }
        public System.Data.Entity.Spatial.DbGeography loc_lat { get; set; }
        public System.Data.Entity.Spatial.DbGeography loc_long { get; set; }
    
        public virtual departamento departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<destino> destino { get; set; }
    }
}
