//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndexTF3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class destino
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public destino()
        {
            this.itinerario = new HashSet<itinerario>();
        }
    
        public int des_id { get; set; }
        public string des_nom { get; set; }
        public int des_loc_id { get; set; }
        public int des_cat_id { get; set; }
        public int des_tem_id { get; set; }
        public string des_des { get; set; }
        public System.Data.Entity.Spatial.DbGeography des_lat { get; set; }
        public System.Data.Entity.Spatial.DbGeography des_lon { get; set; }
    
        public virtual localidad localidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itinerario> itinerario { get; set; }
    }
}
