//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndexTF3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int usu_id { get; set; }
        public string usu_nom_com { get; set; }
        public string usu_con { get; set; }
        public string usu_cel { get; set; }
        public string usu_cor { get; set; }
        public string usu_ali { get; set; }
        public Nullable<int> usu_niv_id { get; set; }
    }
}
